-- hds header_start
--
-- VHDL Entity DigAlarm.AlarmTest.generatedInstance
--
-- Created:
--          by - Hawley001.UNKNOWN (Z314ECEPC11)
--          at - 13:50:08 12/09/02
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.1 (Build 12)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY AlarmTest IS
   PORT( 
      AlarmMin     : IN     std_logic;
      AlarmHour    : IN     std_logic;
      M1           : IN     std_logic_vector (3 DOWNTO 0);
      M2           : IN     std_logic_vector (3 DOWNTO 0);
      H1           : IN     std_logic_vector (3 DOWNTO 0);
      H2           : IN     std_logic_vector (3 DOWNTO 0);
      Alarm        : OUT    std_logic;
      Clock        : IN     std_logic;
      DisplayClock : IN     std_logic_vector (7 DOWNTO 0)
   );

END AlarmTest ;

-- hds interface_end
-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF AlarmTest IS 
BEGIN


END generatedInstance;
