-- hds header_start
--
-- VHDL Entity DigAlarm.DisplayControl.interface
--
-- Created:
--          by - Hawley001.UNKNOWN (Z314ECEPC11)
--          at - 13:55:02 12/09/02
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.1 (Build 12)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY DisplayControl IS
   PORT( 
      Clock        : IN     std_logic;
      DisplayClock : IN     std_logic_vector (7 DOWNTO 0);
      H1           : IN     std_logic_vector (3 DOWNTO 0);
      H2           : IN     std_logic_vector (3 DOWNTO 0);
      M1           : IN     std_logic_vector (3 DOWNTO 0);
      M2           : IN     std_logic_vector (3 DOWNTO 0);
      SEG          : OUT    std_logic_vector (3 DOWNTO 0);
      SegEN        : OUT    std_logic_vector (3 DOWNTO 0)
   );

-- Declarations

END DisplayControl ;

-- hds interface_end
--
-- VHDL Architecture DigAlarm.DisplayControl.fsm
--
-- Created:
--          by - Hawley001.UNKNOWN (Z314ECEPC11)
--          at - 13:55:02 12/09/02
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.1 (Build 12)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE fsm OF DisplayControl IS

   -- Architecture Declarations
   TYPE STATE_TYPE IS (
      s0,
      s1,
      s2,
      s3
   );

   -- State vector declaration
   ATTRIBUTE state_vector : string;
   ATTRIBUTE state_vector OF fsm : ARCHITECTURE IS "current_state" ;


   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE ;
   SIGNAL next_state : STATE_TYPE ;

BEGIN

   ----------------------------------------------------------------------------
   clocked : PROCESS(
      DisplayClock
   )
   ----------------------------------------------------------------------------
   BEGIN
      IF (DisplayClock'EVENT AND DisplayClock == '1') THEN
         current_state <= next_state;
         -- Default Assignment To Internals

      END IF;

   END PROCESS clocked;

   ----------------------------------------------------------------------------
   nextstate : PROCESS (
      DisplayClock,
      current_state
   )
   ----------------------------------------------------------------------------
   BEGIN
      CASE current_state IS
      WHEN s0 =>
         IF (DisplayClock = '1') THEN
            next_state <= s1;
         ELSE
            next_state <= s0;
         END IF;
      WHEN s1 =>
         IF (DisplayClock = '1') THEN
            next_state <= s3;
         ELSE
            next_state <= s1;
         END IF;
      WHEN s2 =>
         IF (DisplayClock = '0') THEN
            next_state <= s0;
         ELSE
            next_state <= s2;
         END IF;
      WHEN s3 =>
         IF (DisplayClock = '1') THEN
            next_state <= s2;
         ELSE
            next_state <= s3;
         END IF;
      WHEN OTHERS =>
         next_state <= s0;
      END CASE;

   END PROCESS nextstate;

   ----------------------------------------------------------------------------
   output : PROCESS (
      DisplayClock,
      H1,
      H2,
      M1,
      M2,
      current_state
   )
   ----------------------------------------------------------------------------
   BEGIN
      -- Default Assignment
      SEG <= "0000";
      SegEN <= "0000";
      -- Default Assignment To Internals

      -- Transition Actions
      CASE current_state IS
      WHEN s0 =>
         IF (DisplayClock = '1') THEN
            SEG <= H2;
            SegEN <="0001";
         END IF;
      WHEN s1 =>
         IF (DisplayClock = '1') THEN
            SEG <= H1;
            SegEN <= "0010";
         END IF;
      WHEN s2 =>
         IF (DisplayClock = '0') THEN
            SEG <= M1;
            SegEN <= "1000";
         END IF;
      WHEN s3 =>
         IF (DisplayClock = '1') THEN
            SEG <= M2;
            SegEN <= "0100";
         END IF;
      WHEN OTHERS =>
         NULL;
      END CASE;

   END PROCESS output;

   -- Concurrent Statements

END fsm;
