-- hds header_start
--
-- VHDL Entity DigAlarm.M1Counter.interface
--
-- Created:
--          by - Hawley001.UNKNOWN (Z314ECEPC11)
--          at - 13:52:37 12/09/02
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.1 (Build 12)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY M1Counter IS
   PORT( 
      Clock        : IN     std_logic;
      DisplayClock : IN     std_logic_vector (7 DOWNTO 0);
      S2overflow   : IN     std_logic;
      TimeMin      : IN     std_logic;
      M1           : OUT    std_logic_vector (3 DOWNTO 0);
      M1overflow   : OUT    std_logic
   );

-- Declarations

END M1Counter ;

-- hds interface_end
--
-- VHDL Architecture DigAlarm.M1Counter.fsm
--
-- Created:
--          by - Hawley001.UNKNOWN (Z314ECEPC11)
--          at - 13:52:37 12/09/02
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.1 (Build 12)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE fsm OF M1Counter IS

   -- Architecture Declarations
   TYPE STATE_TYPE IS (
      s9,
      s8,
      s7,
      s6,
      s10,
      s11,
      s12,
      s13,
      s14,
      s15
   );

   -- State vector declaration
   ATTRIBUTE state_vector : string;
   ATTRIBUTE state_vector OF fsm : ARCHITECTURE IS "current_state" ;


   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE ;
   SIGNAL next_state : STATE_TYPE ;

BEGIN

   ----------------------------------------------------------------------------
   clocked : PROCESS(
      S2overflow
   )
   ----------------------------------------------------------------------------
   BEGIN
      IF (S2overflow'EVENT AND S2overflow = '1') THEN
         current_state <= next_state;
         -- Default Assignment To Internals

      END IF;

   END PROCESS clocked;

   ----------------------------------------------------------------------------
   nextstate : PROCESS (
      S2overflow,
      TimeMin,
      current_state
   )
   ----------------------------------------------------------------------------
   BEGIN
      CASE current_state IS
      WHEN s9 =>
         IF (S2overflow = '1' OR TimeMin = '1') THEN
            next_state <= s6;
         ELSE
            next_state <= s9;
         END IF;
      WHEN s8 =>
         IF (S2overflow = '1' OR TimeMin = '1') THEN
            next_state <= s9;
         ELSE
            next_state <= s8;
         END IF;
      WHEN s7 =>
         IF (S2overflow = '1' OR TimeMin = '1') THEN
            next_state <= s8;
         ELSE
            next_state <= s7;
         END IF;
      WHEN s6 =>
         IF (S2overflow = '1' OR TimeMin = '1') THEN
            next_state <= s10;
         ELSE
            next_state <= s6;
         END IF;
      WHEN s10 =>
         IF (S2overflow = '1' OR TimeMin = '1') THEN
            next_state <= s13;
         ELSE
            next_state <= s10;
         END IF;
      WHEN s11 =>
         IF (S2overflow = '1' OR TimeMin = '1') THEN
            next_state <= s7;
         ELSE
            next_state <= s11;
         END IF;
      WHEN s12 =>
         IF (S2overflow = '1' OR TimeMin = '1') THEN
            next_state <= s11;
         ELSE
            next_state <= s12;
         END IF;
      WHEN s13 =>
         IF (S2overflow = '1' OR TimeMin = '1') THEN
            next_state <= s15;
         ELSE
            next_state <= s13;
         END IF;
      WHEN s14 =>
         IF (S2overflow = '1' OR TimeMin = '1') THEN
            next_state <= s12;
         ELSE
            next_state <= s14;
         END IF;
      WHEN s15 =>
         IF (S2overflow = '1' OR TimeMin = '1') THEN
            next_state <= s14;
         ELSE
            next_state <= s15;
         END IF;
      WHEN OTHERS =>
         next_state <= s6;
      END CASE;

   END PROCESS nextstate;

   ----------------------------------------------------------------------------
   output : PROCESS (
      S2overflow,
      TimeMin,
      current_state
   )
   ----------------------------------------------------------------------------
   BEGIN
      -- Default Assignment
      M1 <= "0000";
      M1overflow <= '0';
      -- Default Assignment To Internals

      -- State Actions
      CASE current_state IS
      WHEN s9 =>
         M1 <= "1001";
      WHEN s8 =>
         M1 <= "1000";
      WHEN s7 =>
         M1 <= "0111";
      WHEN s6 =>
         M1 <= "0000";
      WHEN s10 =>
         M1 <= "0001";
      WHEN s11 =>
         M1 <= "0110";
      WHEN s12 =>
         M1 <= "0101";
      WHEN s13 =>
         M1 <= "0010";
      WHEN s14 =>
         M1 <= "0100";
      WHEN s15 =>
         M1 <= "0011";
      WHEN OTHERS =>
         NULL;
      END CASE;

      -- Transition Actions
      CASE current_state IS
      WHEN s9 =>
         IF (S2overflow = '1' OR TimeMin = '1') THEN
            M1overflow <= '1';
         END IF;
      WHEN OTHERS =>
         NULL;
      END CASE;

   END PROCESS output;

   -- Concurrent Statements

END fsm;
